language: elixir
elixir:
  - 1.13
  - 1.14
otp_release:
  - 22.0
  - 23.0
  - 24.0
install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get --only=test
script:
  - mix test
  - mix format --check-formatted
  - MIX_ENV=test mix credo --strict --format=oneline
  - MIX_ENV=test mix recode --dry
