language: elixir
elixir:
  - 1.9
  - 1.10
  - 1.11
otp_release:
  - 21.0
  - 22.0
  - 23.0
jobs:
  exclude:
  - elixir: 1.9
    otp_release: 23.0
install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get --only=test
script:
  - mix test
  - mix format --check-formatted
  - MIX_ENV=test mix credo --strict --format=oneline
